Changed getopt to libiberty, commented out an aborted attempt at host level Makefiles because it caused errors on +rm, add a warning for directories expected to be removed on +rm but that don't exist.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -175,7 +175,7 @@ fi
 # script appropriate for this directory.  For more information, check
 # any existing configure script.
 
-configdirs="getopt bfd binutils ld gas gcc gnulib clib"
+configdirs="libiberty bfd binutils ld gas gcc gnulib clib"
 srctrigger=README.configure
 srcname="gnu development package"
 
@@ -285,11 +285,15 @@ for host in ${hosts} ; do
 		targetsubdir=Target-${target}
 
 		if [ -n "${removing}" ] ; then
-			if [ -d "${hostsubdir}/${targetsubdir}" ] ; then
-				rm -rf ${hostsubdir}/${targetsubdir}
+			if [ -n "${forcesubdirs}" ] ; then
+				if [ -d "${hostsubdir}" ] ; then
+					rm -rf ${hostsubdir}/${targetsubdir}
 
-				if [ -z "`(ls ${hostsubdir}) 2>&1 | grep Target-`" ] ; then
-					rm -rf ${hostsubdir}
+					if [ -z "`(ls ${hostsubdir}) 2>&1 | grep Target-`" ] ; then
+						rm -rf ${hostsubdir}
+					fi
+				else
+					echo Warning: no `pwd`/${hostsubdir} to remove.
 				fi
 			else
 				rm -f Makefile config.status ${links}
@@ -328,11 +332,12 @@ for host in ${hosts} ; do
 
 			if [ -n "${srctrigger}" -a ! -r ${srcdir}/${srctrigger} ] ; then
 				if [ -z "${srcdirdefaulted}" ] ; then
-				  echo "${progname}: Can't find ${srcname} sources in \`${srcdir}'." 1>&2
+					echo "${progname}: Can't find ${srcname} sources in `pwd`/${srcdir}" 1>&2
 				else
-				  echo "${progname}: Can't find ${srcname} sources in \`.' or \`..'." 1>&2
+					echo "${progname}: Can't find ${srcname} sources in `pwd`/. or `pwd`/.." 1>&2
 				fi
 
+				echo \(At least ${srctrigger} is missing.\) 1>&2
 				exit 1
 			fi
 
@@ -476,8 +481,22 @@ for host in ${hosts} ; do
 			originaldir=`pwd`
 			cd ${srcdir}
 		fi
-	done
-done
+	done # for each target
+
+#	# Now build a Makefile for this host.
+#	if [ -n "${forcesubdirs}" ] ; then
+#		cd ${hostsubdir}
+#		cat > GNUmakefile << E!O!F
+## Makefile generated by configure for host ${host}.
+#
+#%:
+#	for i in ${targets} ; do \
+#		$(MAKE) -C Target-\$i \$@
+#
+#all clean stage1 stage2 stage3 stage4etags tags TAGS
+#E!O!F
+#	fi
+done # for each host
 
 # If there are subdirectories, then recurse. 
 
@@ -553,7 +572,12 @@ exit 0
 
 #
 # $Log$
-# Revision 1.9  1991/04/24 16:50:54  rich
+# Revision 1.10  1991/05/03 19:14:21  rich
+# Changed getopt to libiberty, commented out an aborted attempt at host
+# level Makefiles because it caused errors on +rm, add a warning for
+# directories expected to be removed on +rm but that don't exist.
+#
+# Revision 1.8  1991/04/24  16:50:59  rich
 # Three staging checkpoint.
 #
 # Revision 1.7  1991/04/17  01:34:47  rich
