* coffread.c (coff_sym_fns): Add default_symfile_segments. 	* dbxread.c (start_psymtab): Check HAVE_ELF. 	(aout_sym_fns): Likewise. 	* elfread.c (elf_symfile_segments): New. 	(elf_sym_fns): Add elf_symfile_segments. 	* mipsread.c (ecoff_sym_fns): Add default_symfile_segments. 	* remote.c (get_offsets): Use symfile_map_offsets_to_segments. 	Skip if there is no symfile_objfile.  Handle TextSeg and DataSeg. 	* somread.c (som_sym_fns): Use default_symfile_segments. 	* symfile.c (find_sym_fns): Take a BFD and return the sym_fns. 	(init_objfile_sect_indices): Call symfile_find_segment_sections. 	(default_symfile_segments): New function. 	(syms_from_objfile): Update call to find_sym_fns. 	(symfile_get_segment_data, free_symfile_segment_data): New. 	(symfile_map_offsets_to_segments): New. 	(symfile_find_segment_sections): New. 	* symfile.h (struct symfile_segment_data): New. 	(struct sym_fns): Add sym_segments. 	(default_symfile_segments, symfile_get_segment_data) 	(free_symfile_segment_data): New prototypes. 	(symfile_map_offsets_to_segments): Likewise. 	* xcoffread.c (xcoff_sym_fns): Add default_symfile_segments. 	* Makefile.in (COMMON_OBS): Remove elfread.o. 	(elf_internal_h): New. 	(elfread.o): Update. 	* configure.ac: Add elfread.o to COMMON_OBS if bfd/elf.o was 	compiled. 	* config.in, configure: Regenerated. 	* NEWS: Mention qOffsets changes.
	* gdb.texinfo (General Query Packets): Document qOffsets changes.

	* Makefile.def: Add dependency from configure-gdb to all-bfd.
	* Makefile.in: Regenerated.

diff --git a/gdb/configure b/gdb/configure
--- a/gdb/configure
+++ b/gdb/configure
@@ -21797,6 +21797,82 @@ _ACEOF
 esac
 
 
+# Add ELF support to GDB, but only if BFD includes ELF support.
+OLD_CFLAGS=$CFLAGS
+OLD_LDFLAGS=$LDFLAGS
+OLD_LIBS=$LIBS
+CFLAGS="$CFLAGS -I${srcdir}/../include -I${objdir}/../bfd -I${srcdir}/../bfd"
+LDFLAGS="$LDFLAGS -L../bfd -L../libiberty"
+LIBS="$LIBS -lbfd -liberty"
+echo "$as_me:$LINENO: checking for ELF support in BFD" >&5
+echo $ECHO_N "checking for ELF support in BFD... $ECHO_C" >&6
+if test "${gdb_cv_var_elf+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <stdlib.h>
+#include "bfd.h"
+#include "elf-bfd.h"
+
+int
+main ()
+{
+bfd *abfd = NULL; bfd_get_elf_phdr_upper_bound (abfd);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  gdb_cv_var_elf=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+gdb_cv_var_elf=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $gdb_cv_var_elf" >&5
+echo "${ECHO_T}$gdb_cv_var_elf" >&6
+if test $gdb_cv_var_elf = yes; then
+  CONFIG_OBS="$CONFIG_OBS elfread.o"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ELF 1
+_ACEOF
+
+fi
+CFLAGS=$OLD_CFLAGS
+LDFLAGS=$OLD_LDFLAGS
+LIBS=$OLD_LIBS
+
 # Add any host-specific objects to GDB.
 CONFIG_OBS="${CONFIG_OBS} ${gdb_host_obs}"
 
