1998-10-19  Jason Molenda  (jsm@bugshack.cygnus.com)
        * configure.in (AM_EXEEXT): Use AC_EXEEXT instead.
        * configure: Regenerated.


Geoff just removed the AM_EXEEXT definition from ../binutils/aclocal.m4
so we would have been hosed in the near future.

diff --git a/gdb/configure b/gdb/configure
--- a/gdb/configure
+++ b/gdb/configure
@@ -5974,9 +5974,9 @@ fi
 
 
 
-echo $ac_n "checking for Cygwin32 environment""... $ac_c" 1>&6
-echo "configure:5979: checking for Cygwin32 environment" >&5
-if eval "test \"`echo '$''{'am_cv_cygwin32'+set}'`\" = set"; then
+echo $ac_n "checking for cygwin32 environment""... $ac_c" 1>&6
+echo "configure:5979: checking for cygwin32 environment" >&5
+if eval "test \"`echo '$''{'ac_cv_cygwin32'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
@@ -5989,23 +5989,23 @@ return __CYGWIN32__;
 EOF
 if { (eval echo configure:5991: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
-  am_cv_cygwin32=yes
+  ac_cv_cygwin32=yes
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -rf conftest*
-  am_cv_cygwin32=no
+  ac_cv_cygwin32=no
 fi
 rm -f conftest*
 rm -f conftest*
 fi
 
-echo "$ac_t""$am_cv_cygwin32" 1>&6
+echo "$ac_t""$ac_cv_cygwin32" 1>&6
 CYGWIN32=
-test "$am_cv_cygwin32" = yes && CYGWIN32=yes
-echo $ac_n "checking for Mingw32 environment""... $ac_c" 1>&6
-echo "configure:6008: checking for Mingw32 environment" >&5
-if eval "test \"`echo '$''{'am_cv_mingw32'+set}'`\" = set"; then
+test "$ac_cv_cygwin32" = yes && CYGWIN32=yes
+echo $ac_n "checking for mingw32 environment""... $ac_c" 1>&6
+echo "configure:6008: checking for mingw32 environment" >&5
+if eval "test \"`echo '$''{'ac_cv_mingw32'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
@@ -6018,52 +6018,52 @@ return __MINGW32__;
 EOF
 if { (eval echo configure:6020: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
-  am_cv_mingw32=yes
+  ac_cv_mingw32=yes
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -rf conftest*
-  am_cv_mingw32=no
+  ac_cv_mingw32=no
 fi
 rm -f conftest*
 rm -f conftest*
 fi
 
-echo "$ac_t""$am_cv_mingw32" 1>&6
+echo "$ac_t""$ac_cv_mingw32" 1>&6
 MINGW32=
-test "$am_cv_mingw32" = yes && MINGW32=yes
+test "$ac_cv_mingw32" = yes && MINGW32=yes
 
 
 echo $ac_n "checking for executable suffix""... $ac_c" 1>&6
 echo "configure:6039: checking for executable suffix" >&5
-if eval "test \"`echo '$''{'am_cv_exeext'+set}'`\" = set"; then
+if eval "test \"`echo '$''{'ac_cv_exeext'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   if test "$CYGWIN32" = yes || test "$MINGW32" = yes; then
-am_cv_exeext=.exe
+  ac_cv_exeext=.exe
 else
-cat > am_c_test.c << 'EOF'
-int main() {
-/* Nothing needed here */
-}
-EOF
-${CC-cc} -o am_c_test $CFLAGS $CPPFLAGS $LDFLAGS am_c_test.c $LIBS 1>&5
-am_cv_exeext=
-for file in am_c_test.*; do
-   case $file in
-    *.c) ;;
-    *.o) ;;
-    *) am_cv_exeext=`echo $file | sed -e s/am_c_test//` ;;
-   esac
-done
-rm -f am_c_test*
+  rm -f conftest*
+  echo 'int main () { return 0; }' > conftest.$ac_ext
+  ac_cv_exeext=
+  if { (eval echo configure:6049: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; }; then
+    for file in conftest.*; do
+      case $file in
+      *.c | *.o | *.obj | *.ilk | *.pdb) ;;
+      *) ac_cv_exeext=`echo $file | sed -e s/conftest//` ;;
+      esac
+    done
+  else
+    { echo "configure: error: installation or configuration problem: compiler cannot create executables." 1>&2; exit 1; }
+  fi
+  rm -f conftest*
+  test x"${ac_cv_exeext}" = x && ac_cv_exeext=no
+fi
 fi
 
-test x"${am_cv_exeext}" = x && am_cv_exeext=no
-fi
 EXEEXT=""
-test x"${am_cv_exeext}" != xno && EXEEXT=${am_cv_exeext}
-echo "$ac_t""${am_cv_exeext}" 1>&6
+test x"${ac_cv_exeext}" != xno && EXEEXT=${ac_cv_exeext}
+echo "$ac_t""${ac_cv_exeext}" 1>&6
+ac_exeext=$EXEEXT
 
 
 subdirs="$configdirs"
