Minor polish & config mapping.

diff --git a/bfd/configure b/bfd/configure
--- a/bfd/configure
+++ b/bfd/configure
@@ -55,6 +55,7 @@ hostsubdir=
 Makefile=Makefile
 Makefile_in=Makefile.in
 norecurse=
+recursing=
 removing=
 srcdir=
 srctrigger=
@@ -92,6 +93,9 @@ do
 	-norecurse | +no*)
 		norecurse=true
 		;;
+	-recursing)
+		recursing=true
+		;;
 	-rm | +r*)
 		removing=${arg}
 		;;
@@ -118,7 +122,7 @@ do
 	-* | +*)
 		(echo ;
 		echo "Unrecognized option: \"${arg}\"". ;
-		echo) 2>&1
+		echo) 1>&2
 		fatal=true
 		;;
 	*)
@@ -134,7 +138,6 @@ done
 
 if [ -n "${verbose}" ] ; then
 	echo `pwd`/configure $*
-	echo targets=\"${targets}\"
 fi
 
 # process host and target only if not rebuilding configure itself or removing.
@@ -143,7 +146,7 @@ if [ -z "${template}" -a -z "${removing}" -a -z "${fatal}" ] ; then
 	if [ -z "${hosts}" ] ; then
 		(echo ;
 		echo "configure: No HOST specified." ;
-		echo) 2>&1
+		echo) 1>&2
 		fatal=true
 	fi
 fi
@@ -166,7 +169,7 @@ if [ -n "${fatal}" -o "${hosts}" = "help" ] ; then
 	echo ;
 	echo "Where HOST and TARGET are something like \"vax\", \"sun3\", \"encore\", etc." ;
 	echo "Asking for more than one \"+target\" implies \"+subdirs\".  Any other" ;
-	echo "options given will apply to all targets.") 2>&1
+	echo "options given will apply to all targets.") 1>&2
 
 	if [ -r config.status ] ; then
 		cat config.status
@@ -183,14 +186,13 @@ fi
 
 srctrigger=libbfd.c
 srcname="bfd"
-commontargets=true
 
 ## end of common part.
 
 # are we rebuilding config itself?
 if [ -n "${template}" ] ; then
 	if [ ! -r ${template} ] ; then
-		echo '***' "Can't find template ${template}." 2>&1
+		echo '***' "Can't find template ${template}." 1>&2
 		exit 1
 	fi
 
@@ -211,12 +213,12 @@ if [ -n "${template}" ] ; then
 
 	if [ -r configure.in ] ; then
 		if [ -z "`grep '^# per\-host:' configure.in`" ] ; then
-			echo '***' `pwd`/configure.in has no "per-host:" line. 2>&1
+			echo '***' `pwd`/configure.in has no "per-host:" line. 1>&2
 			exit 1
 		fi
 
 		if [ -z "`grep '^# per\-target:' configure.in`" ] ; then
-			echo '***' `pwd`/configure.in has no "per-target:" line. 2>&1
+			echo '***' `pwd`/configure.in has no "per-target:" line. 1>&2
 			exit 1
 		fi
 
@@ -254,6 +256,17 @@ if [ -n "${template}" ] ; then
 		echo Rebuilt configure in `pwd`
 	fi
 
+	# Now update config.sub from the template directory.
+	if echo "$template" | grep -s 'configure$' ; then
+		cp `echo "$template" | sed s/configure$/config.sub/` ./config.sub.new
+	#	mv config.sub config.sub.old
+		mv config.sub.new config.sub
+
+		if [ -n "${verbose}" ] ; then
+			echo Rebuilt config.sub in `pwd`
+		fi
+	fi
+
 	if [ -z "${norecurse}" ] ; then
 		# If template is relative path, make it absolute for recursing.
 		if echo "${template}" | grep -s '^/' ; then
@@ -281,7 +294,9 @@ if [ -n "${template}" ] ; then
 						echo Warning: No configure script in `pwd`/$i
 					fi
 				else
-					echo Warning: directory $i is missing.
+					if [ -n "${verbose}" ] ; then
+					  echo Warning: directory $i is missing.
+					fi
 				fi
 			done
 		done
@@ -303,31 +318,133 @@ for host in ${hosts} ; do
 		defaulttargets=true
 	fi
 
+	result=`/bin/sh ./config.sub ${host}`
+	host_cpu=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\1/'`
+	host_vendor=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\2/'`
+	host_os=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\3/'`
+	host=${host_cpu}-${host_vendor}-${host_os}
 	host_makefile_frag=config/hmake-${host}
 
 #### configure.in per-host parts come in here.
 
-if [ ! -f config/hmake-${host} ] ; then
-	echo No such host available: ${host}
+if [ "${host_os}" = "posix" ] ; then
+	bfd_host=posix
+else
+	case "${host_cpu}" in
+	rs6000)	bfd_host=aix ;;
+	mips)
+		case "${host_vendor}" in
+		dec)	bfd_host=dec3100 ;;
+		esac
+		;;
+	m88k)
+		case "${host_vendor}" in
+		*)
+			case "${host_os}" in
+			dgux)	bfd_host=dgux ;;
+			esac
+			;;
+		esac
+		;;
+
+	m68k)
+		case "${host_vendor}" in
+		hp)	
+			case "${host_os}" in
+			hpux)	bfd_host=hp9000 ;;
+			bsd)	bfd_host=hp300bsd ;;
+			esac
+			;;
+		sony)	bfd_host=news ;;
+		sun)	bfd_host=sun3 ;;
+		esac
+		;;
+
+	i386)
+		case "${host_vendor}" in
+		*)
+			case "${host_os}" in
+			sysv)	bfd_host=i386v ;;
+			esac
+			;;
+		esac
+		;;
+
+	sparc)
+		case "${host_vendor}" in
+		sun)	bfd_host=sun4 ;;
+		esac
+		;;
+
+	rtpc)	bfd_host=rtbsd ;;
+	tahoe | vax)	bfd_host=${host_cpu} ;;
+	esac
+fi
+
+if [ ! -f config/hmake-${bfd_host} ] ; then
+	echo '***' BFD does not support host ${host}: no file config/hmake-${bfd_host}
 	exit 1
 fi
+
+host_makefile_frag=config/hmake-${bfd_host}
 
 ## end of per-host part.
 
 	for target in ${targets} ; do
 
-		if [ -n "${verbose}" ] ; then
-			echo "	target=\"${target}\""
-		fi
-
+		result=`/bin/sh ./config.sub ${target}`
+		target_cpu=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\1/'`
+		target_vendor=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\2/'`
+		target_os=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\3/'`
+		target=${target_cpu}-${target_vendor}-${target_os}
 		target_makefile_frag=config/tmake-${target}
 
 #### configure.in per-target parts come in here.
 
-if [ ! -f config/tmake-${target} ] ; then
-	echo No such target available: ${target}
+case "${target_vendor}" in
+aout | coff | bout) bfd_target=${target_cpu}-${target_vendor} ;;
+sony)	bfd_target=news ;;
+intel)	bfd_target=${target_cpu}-coff ;;	
+wrs)
+	case "${target_cpu}" in
+	i960) bfd_target=i960-bout ;;
+	m68k) bfd_target=m68k-aout ;;
+	esac
+	;;
+sun)
+	case "${target_cpu}" in
+	m68k)	bfd_target=sun3 ;;
+	sparc)	bfd_target=sun4 ;;
+	esac
+	;;
+dec)
+	case "${target_cpu}" in
+	mips) bfd_target=dec3100 ;;
+	esac
+	;;
+hp)
+	case "${target_cpu}" in
+	m68k)
+		case "${target_os}" in
+		hpux)	bfd_target=hp9000 ;;
+		bsd)	bfd_target=hp300bsd ;;
+		esac
+		;;
+	esac
+	;;
+*)
+	case "${target_cpu}" in
+	tahoe | vax) bfd_target=${target_cpu} ;;
+	esac
+	;;
+esac
+
+if [ ! -f config/tmake-${bfd_target} ] ; then
+	echo '***' BFD does not support target ${target}: no file config/tmake-${bfd_target}
 	exit 1
 fi
+
+target_makefile_fragment=config/tmake-${bfd_target}
 
 files=
 links=
@@ -355,7 +472,7 @@ links=
 			if [ -n "${subdirs}" ] ; then
 				# check for existing status before allowing forced subdirs.
 				if [ -f ${Makefile} ] ; then
-					echo '***' "${Makefile} already exists in source directory.  `pwd` not configured." 2>&1
+					echo '***' "${Makefile} already exists in source directory.  `pwd` not configured." 1>&2
 					exit 1
 				fi
 
@@ -380,7 +497,7 @@ links=
 			else
 				# if not subdir builds, then make sure none exist.
 				if [ -n "`(ls .) 2>&1 | grep Host-`" ] ; then
-					echo '***' "Configured subdirs exist.  `pwd` not configured." 2>&1
+					echo '***' "Configured subdirs exist.  `pwd` not configured." 1>&2
 					exit 1
 				fi
 			fi
@@ -396,12 +513,12 @@ links=
 
 			if [ -n "${srctrigger}" -a ! -r ${srcdir}/${srctrigger} ] ; then
 				if [ -z "${srcdirdefaulted}" ] ; then
-					echo '***' "${progname}: Can't find ${srcname} sources in `pwd`/${srcdir}" 2>&1
+					echo '***' "${progname}: Can't find ${srcname} sources in `pwd`/${srcdir}" 1>&2
 				else
-					echo '***' "${progname}: Can't find ${srcname} sources in `pwd`/. or `pwd`/.." 2>&1
+					echo '***' "${progname}: Can't find ${srcname} sources in `pwd`/. or `pwd`/.." 1>&2
 				fi
 
-				echo '***' \(At least ${srctrigger} is missing.\) 2>&1
+				echo '***' \(At least ${srctrigger} is missing.\) 1>&2
 				exit 1
 			fi
 
@@ -415,8 +532,8 @@ links=
 				set ${links}; link=$1; shift; links=$*
 
 				if [ ! -r ${srcdir}/${file} ] ; then
-					echo '***' "${progname}: cannot create a link \"${link}\"," 2>&1
-					echo '***' "since the file \"${file}\" does not exist." 2>&1
+					echo '***' "${progname}: cannot create a link \"${link}\"," 1>&2
+					echo '***' "since the file \"${file}\" does not exist." 1>&2
 					exit 1
 				fi
 
@@ -426,7 +543,7 @@ links=
 				${symbolic_link} ${srcdir}/${file} ${link} 2>/dev/null || ${hard_link} ${srcdir}/${file} ${link}
 
 				if [ ! -r ${link} ] ; then
-					echo '***' "${progname}: unable to link \"${link}\" to \"${srcdir}/${file}\"." 2>&1
+					echo '***' "${progname}: unable to link \"${link}\" to \"${srcdir}/${file}\"." 1>&2
 					exit 1
 				fi
 
@@ -525,7 +642,7 @@ links=
 				andusing=${using}
 			fi
 
-			if [ -n "${verbose}" ] ; then
+			if [ -n "${verbose}" -o -z "${recursing}" ] ; then
 				echo "Created \"${Makefile}\"" in `pwd`${andusing}.
 			fi
 
@@ -546,6 +663,26 @@ links=
 			originaldir=`pwd`
 			cd ${srcdir}
 		fi
+
+		# If there are subdirectories, then recurse. 
+		if [ -z "${norecurse}" -a -n "${configdirs}" ] ; then 
+			for configdir in ${configdirs} ; do
+				if [ -n "${verbose}" ] ; then
+					echo Configuring ${configdir}...
+				fi
+
+				if [ -d ${configdir} ] ; then
+					(cd ${configdir} ;
+						./configure -recursing ${host} +target=${target} \
+							${verbose} ${subdirs} ${removing} +destdir=${destdir}) \
+						| sed 's/^/	/'
+				else
+					if [ -n "${verbose}" ] ; then
+						echo Warning: directory \"${configdir}\" is missing.
+					fi
+				fi
+			done
+		fi
 	done # for each target
 
 	# Now build a Makefile for this host.
@@ -565,100 +702,17 @@ E!O!F
 	fi
 done # for each host
 
-# If there are subdirectories, then recurse. 
-
-if [ -n "${norecurse}" -o -z "${configdirs}" ] ; then exit 0 ; fi
-
-# configdirs is not null
-for configdir in ${configdirs} ; do
-	if [ -n "${verbose}" ] ; then
-		echo Configuring ${configdir}...
-	fi
-
-	specifics=
-	commons=
-
-	if [ -n "${defaulttargets}" ] ; then
-		for host in ${hosts} ; do
-			if [ -d ${configdir}.${host} ] ; then
-				newspecifics="${specifics} ${host}"
-				specifics=${newspecifics}
-			else
-				newcommons="${commons} ${host}"
-				commons=${newcommons}
-			fi # if target specific
-		done # for each host
-
-		if [ -n "${commons}" ] ; then
-			if [ -d ${configdir} ] ; then
-				(cd ${configdir} ;
-					./configure ${commons} ${verbose} ${subdirs} ${removing} +destdir=${destdir}) \
-					| sed 's/^/	/'
-			else
-				echo Warning: directory \"${configdir}\" is missing.
-			fi
-		fi # if any common hosts
-
-		if [ -n "${specifics}" ] ; then
-			for host in ${specifics} ; do
-				if [ -n "${verbose} ] ; then
-					echo Configuring target specific directory ${configdir}.${host}...
-				fi
-
-				(cd ${configdir}.${host} ;
-					./configure ${host} ${verbose} ${subdirs} ${removing} +destdir=${destdir}) \
-					| sed 's/^/	/'
-			done # for host in specifics
-		fi # if there are any specifics
-	else
-
-		for target in ${targets} ; do
-			if [ -d ${configdir}.${target} ] ; then
-				newspecifics="${specifics} ${target}"
-				specifics=${newspecifics}
-			else
-				newcommons="${commons} +target=${target}"
-				commons=${newcommons}
-			fi
-
-		done # check for target specific dir override
-
-		if [ -n "${verbose}" ] ; then
-			echo "	"commons=\"${commons}\"
-			echo "	"specifics=\"${specifics}\"
-		fi # if verbose
-
-		if [ -n "${commons}" ] ; then
-			if [ -d ${configdir} ] ; then
-				(cd ${configdir} ;
-					./configure ${hosts} ${verbose} ${subdirs} ${removing} \
-						${commons} +destdir=${destdir}) \
-					| sed 's/^/	/'
-			else
-				echo Warning: directory \"${configdir}\" is missing.
-			fi
-		fi # if any commons
-
-		if [ -n "${specifics}" ] ; then
-			for target in ${specifics} ; do
-				if [ -n "${verbose} ] ; then
-					echo Configuring target specific directory ${configdir}.${target}...
-				fi
-
-				(cd ${configdir}.${target} ;
-					./configure ${hosts} ${verbose} ${subdirs} ${removing} \
-						"+target=${target}" +destdir=${destdir}) \
-					| sed 's/^/	/'
-			done
-		fi # if any specifics
-	fi # not default targets
-done
-
 exit 0
 
 #
 # $Log$
-# Revision 1.20  1991/08/20 04:56:40  rich
+# Revision 1.22  1991/08/23 03:31:43  rich
+# Minor polish & config mapping.
+#
+# Revision 1.30  1991/08/22  07:15:51  rich
+# Three part names, etc.
+#
+# Revision 1.29  1991/08/20  04:56:51  rich
 # revisiting error messages
 #
 # Revision 1.28  1991/08/16  19:22:17  rich
