Rename switch to enable/disable -Werror to --enable-werror/--disable-werror for compatibility with gcc.

diff --git a/bfd/configure b/bfd/configure
--- a/bfd/configure
+++ b/bfd/configure
@@ -859,7 +859,7 @@ Optional Features:
   --enable-64-bit-bfd     64-bit support (on hosts with narrower word sizes)
   --enable-targets        alternative target configurations
   --enable-commonbfdlib   build shared BFD/opcodes/libiberty library
-  --enable-error-on-warning    treat compile warnings as errors
+  --enable-werror    treat compile warnings as errors
   --enable-build-warnings Enable build-time compiler warnings if gcc is used
   --enable-maintainer-mode  enable make rules and dependencies not useful
 			  (and sometimes confusing) to the casual installer
@@ -4265,19 +4265,19 @@ else
 fi;
 build_warnings="-W -Wall -Wstrict-prototypes -Wmissing-prototypes"
 
-# Check whether --enable-error-on-warning or --disable-error-on-warning was given.
-if test "${enable_error_on_warning+set}" = set; then
-  enableval="$enable_error_on_warning"
+# Check whether --enable-werror or --disable-werror was given.
+if test "${enable_werror+set}" = set; then
+  enableval="$enable_werror"
   case "${enableval}" in
      yes | y) ERROR_ON_WARNING="yes" ;;
      no | n)  ERROR_ON_WARNING="no" ;;
-     *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-error-on-warning" >&5
-echo "$as_me: error: bad value ${enableval} for --enable-error-on-warning" >&2;}
+     *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-werror" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-werror" >&2;}
    { (exit 1); exit 1; }; } ;;
    esac
 fi;
 
-# Enable -Werror by default, suppressing it only for --disable-error-on-warning
+# Enable -Werror by default, suppressing it only for --disable-werror
 # or --disable-build-warnings.
 if test "${ERROR_ON_WARNING}" != no
 then
diff --git a/ld/configure b/ld/configure
--- a/ld/configure
+++ b/ld/configure
@@ -32,7 +32,7 @@ ac_help="$ac_help
 ac_help="$ac_help
   --with-sysroot[=DIR] Search for usr/lib et al within DIR."
 ac_help="$ac_help
-  --enable-error-on-warning    treat compile warnings as errors"
+  --enable-werror    treat compile warnings as errors"
 ac_help="$ac_help
   --enable-build-warnings enable build-time compiler warnings if gcc is used"
 ac_help="$ac_help
@@ -2262,24 +2262,24 @@ fi
 
 build_warnings="-W -Wall -Wstrict-prototypes -Wmissing-prototypes"
 
-# Check whether --enable-error-on-warning or --disable-error-on-warning was given.
-if test "${enable_error_on_warning+set}" = set; then
-  enableval="$enable_error_on_warning"
+# Check whether --enable-werror or --disable-werror was given.
+if test "${enable_werror+set}" = set; then
+  enableval="$enable_werror"
   case "${enableval}" in
      yes | y) ERROR_ON_WARNING="yes" ;;
      no | n)  ERROR_ON_WARNING="no" ;;
-     *) { echo "configure: error: bad value ${enableval} for --enable-error-on-warning" 1>&2; exit 1; } ;;
+     *) { echo "configure: error: bad value ${enableval} for --enable-werror" 1>&2; exit 1; } ;;
    esac
 fi
 
 
-# Enable -Werror by default, suppressing it only for --disable-error-on-warning
+# Enable -Werror by default, suppressing it only for --disable-werror
 # or --disable-build-warnings.
 if test "${ERROR_ON_WARNING}" != no
 then
   build_warnings="$build_warnings -Werror"
 fi
-		   
+
 # Check whether --enable-build-warnings or --disable-build-warnings was given.
 if test "${enable_build_warnings+set}" = set; then
   enableval="$enable_build_warnings"
