Three part names & all.

diff --git a/ld/configure b/ld/configure
--- a/ld/configure
+++ b/ld/configure
@@ -55,11 +55,13 @@ hostsubdir=
 Makefile=Makefile
 Makefile_in=Makefile.in
 norecurse=
+recursing=
 removing=
 srcdir=
 srctrigger=
 target=
 targets=
+commontargets=
 targetsubdir=
 template=
 verbose=
@@ -67,51 +69,54 @@ verbose=
 for arg in $*;
 do
 	case ${arg} in
-	-ansi | +ansi)
+	-ansi | +a*)
 		ansi=true
+		clib=clib
 		;;
 	-destdir=* | +destdir=* | +destdi=* | +destd=* | +dest=* | +des=* | +de=* | +d=*)
 		destdir=`echo ${arg} | sed 's/[+-]d[a-z]*=//'`
-		;;
-	-forcesubdirs | +forcesubdirs | +forcesubdir | +forcesubdi | +forcesubd \
-	| +forcesub | +forcesu | +forces | +force | +forc | +for | +fo | +f)
-		forcesubdirs=${arg}
 		;;
 	-languages=* | +languages=* | +language=* | +languag=* \
 		| +langua=* | +langu=* | +lang=* | +lan=* | +la=* \
 		| +l=*)
 		languages="${languages} `echo ${arg} | sed 's/[+-]l[a-z]*=//'`"
 		;;
-	-gas | +gas | +ga | +g)
+	-gas | +g*)
 		gas=yes
 		;;
-	-help | +h | +help)
+	-help | +h*)
 		fatal=true
 		;;
-	-nfp | +nfp | +nf | +n)
+	-nfp | +nf*)
 		nfp=yes
 		;;
-	-norecurse | +norecurse)
+	-norecurse | +no*)
 		norecurse=true
 		;;
-	-rm | +rm)
+	-recursing)
+		recursing=true
+		;;
+	-rm | +r*)
 		removing=${arg}
 		;;
 #	-srcdir=* | +srcdir=* | +srcdi=* | +srcd=* | +src=* | +sr=* | +s=*)
 #		srcdir=`echo ${arg} | sed 's/[+-]s[a-z]*=//'`
 #		;;
-	-target=* | +target=* | +targe=* | +targ=* | +tar=* | +ta=* | +t=*)
+	-subdirs | +f* | +su*)
+		subdirs=${arg}
+		;;
+	-target=* | +target=* | +targe=* | +targ=* | +tar=* | +ta=*)
 		if [ -n "${targets}" ] ; then
-			forcesubdirs="+forcesubdirs"
+			subdirs="+subdirs"
 		fi
 
 		newtargets="${targets} `echo ${arg} | sed 's/[+-]t[a-z]*=//'`"
 		targets="${newtargets}"
 		;;
-	-template=* | +template=*)
+	-template=* | +template=* | +templat=* | +templa=* | +templ=* | +temp=* | +tem=* | +te=*)
 		template=`echo ${arg} | sed 's/[+-]template=//'`
 		;;
-	+verbose | +verbos | +verbo | +verb | +ver | +ve | +v)
+	-v | -verbose | +v*)
 		verbose=${arg}
 		;;
 	-* | +*)
@@ -122,7 +127,7 @@ do
 		;;
 	*)
 		if [ -n "${hosts}" ] ; then
-			forcesubdirs="+forcesubdirs"
+			subdirs="+subdirs"
 		fi
 
 		newhosts="${hosts} ${arg}"
@@ -133,7 +138,6 @@ done
 
 if [ -n "${verbose}" ] ; then
 	echo `pwd`/configure $*
-	echo targets=\"${targets}\"
 fi
 
 # process host and target only if not rebuilding configure itself or removing.
@@ -142,7 +146,7 @@ if [ -z "${template}" -a -z "${removing}" -a -z "${fatal}" ] ; then
 	if [ -z "${hosts}" ] ; then
 		(echo ;
 		echo "configure: No HOST specified." ;
-		echo) 2>&1
+		echo) 1>&2
 		fatal=true
 	fi
 fi
@@ -153,7 +157,7 @@ if [ -n "${fatal}" -o "${hosts}" = "help" ] ; then
 	echo "Options: [defaults in brackets]" ;
 	echo " +ansi		configure w/ANSI library. [no ansi lib]" ;
 	echo " +destdir=MYDIR	configure for installation into MYDIR. [/usr/local]" ;
-	echo " +forcesubdirs	configure in subdirectories.  [in source directories]" ;
+	echo " +subdirs		configure in subdirectories.  [in source directories]" ;
 	echo " +lang=LANG	configure to build LANG. [gcc]" ;
 	echo " +help		print this message. [normal config]" ;
 	echo " +gas		configure the compilers for use with gas. [native as]" ;
@@ -164,7 +168,7 @@ if [ -n "${fatal}" -o "${hosts}" = "help" ] ; then
 	echo " +template=TEM	rebuild configure using TEM. [normal config]" ;
 	echo ;
 	echo "Where HOST and TARGET are something like \"vax\", \"sun3\", \"encore\", etc." ;
-	echo "Asking for more than one \"+target\" implies \"+forcesubdirs\".  Any other" ;
+	echo "Asking for more than one \"+target\" implies \"+subdirs\".  Any other" ;
 	echo "options given will apply to all targets.") 1>&2
 
 	if [ -r config.status ] ; then
@@ -180,7 +184,6 @@ fi
 # script appropriate for this directory.  For more information, check
 # any existing configure script.
 
-configdirs=
 srctrigger=ldmain.c
 srcname="linker"
 
@@ -189,7 +192,7 @@ srcname="linker"
 # are we rebuilding config itself?
 if [ -n "${template}" ] ; then
 	if [ ! -r ${template} ] ; then
-		echo "Can't find template ${template}."
+		echo '***' "Can't find template ${template}." 1>&2
 		exit 1
 	fi
 
@@ -210,12 +213,12 @@ if [ -n "${template}" ] ; then
 
 	if [ -r configure.in ] ; then
 		if [ -z "`grep '^# per\-host:' configure.in`" ] ; then
-			echo `pwd`/configure.in has no "per-host:" line.
+			echo '***' `pwd`/configure.in has no "per-host:" line. 1>&2
 			exit 1
 		fi
 
 		if [ -z "`grep '^# per\-target:' configure.in`" ] ; then
-			echo `pwd`/configure.in has no "per-target:" line.
+			echo '***' `pwd`/configure.in has no "per-target:" line. 1>&2
 			exit 1
 		fi
 
@@ -248,7 +251,21 @@ if [ -n "${template}" ] ; then
 	rm template.new
 #	mv configure configure.old
 	mv configure.new configure
-	echo Rebuilt configure in `pwd`
+
+	if [ -n "${verbose}" ] ; then
+		echo Rebuilt configure in `pwd`
+	fi
+
+	# Now update config.sub from the template directory.
+	if echo "$template" | grep -s 'configure$' ; then
+		cp `echo "$template" | sed s/configure$/config.sub/` ./config.sub.new
+	#	mv config.sub config.sub.old
+		mv config.sub.new config.sub
+
+		if [ -n "${verbose}" ] ; then
+			echo Rebuilt config.sub in `pwd`
+		fi
+	fi
 
 	if [ -z "${norecurse}" ] ; then
 		# If template is relative path, make it absolute for recursing.
@@ -274,10 +291,12 @@ if [ -n "${template}" ] ; then
 						(cd $i ;
 							./configure +template=${template} ${verbose})
 					else
-						echo No configure script in `pwd`/$i
+						echo Warning: No configure script in `pwd`/$i
 					fi
 				else
-					echo Warning: directory $i is missing.
+					if [ -n "${verbose}" ] ; then
+					  echo Warning: directory $i is missing.
+					fi
 				fi
 			done
 		done
@@ -288,7 +307,7 @@ fi
 
 # some sanity checks on configure.in
 if [ -z "${srctrigger}" ] ; then
-	echo srctrigger not set in configure.in. `pwd` not configured.
+	echo Warning: srctrigger not set in configure.in. `pwd` not configured.
 	exit 1
 fi
 
@@ -299,23 +318,98 @@ for host in ${hosts} ; do
 		defaulttargets=true
 	fi
 
+	result=`/bin/sh ./config.sub ${host}`
+	host_cpu=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\1/'`
+	host_vendor=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\2/'`
+	host_os=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\3/'`
+	host=${host_cpu}-${host_vendor}-${host_os}
 	host_makefile_frag=config/hmake-${host}
 
 #### configure.in per-host parts come in here.
 
-## end of per-host part.
+if [ "${host_os}" = "posix" ] ; then
+	my_host=posix
+else
+	case "${host_cpu}" in
+	rs6000)	my_host=aix ;;
+	mips)
+		case "${host_vendor}" in
+		dec)	my_host=dec3100 ;;
+		esac
+		;;
+	m88k)
+		case "${host_vendor}" in
+		*)
+			case "${host_os}" in
+			dgux)	my_host=dgux ;;
+			esac
+			;;
+		esac
+		;;
 
+	m68k)
+		case "${host_vendor}" in
+		hp)	my_host=hp9000 ;;
+		sony)	my_host=news ;;
+		sun)	my_host=sun3 ;;
+		esac
+		;;
+
+	i386)
+		case "${host_vendor}" in
+		*)
+			case "${host_os}" in
+			sysv)	my_host=i386v ;;
+			esac
+			;;
+		esac
+		;;
+
+	sparc)
+		case "${host_vendor}" in
+		sun)	my_host=sun4 ;;
+		esac
+		;;
+
+	rtpc)	my_host=rtbsd ;;
+	tahoe | vax)	my_host=${host_cpu} ;;
+	esac
+fi
+
+if [ ! -f config/hmake-${my_host} ] ; then
+	echo '***' Binutils do not support host ${host}
+	exit 1
+fi
+
+host_makefile_frag=config/hmake-${my_host}
+
+## end of per-host part.
 
 	for target in ${targets} ; do
 
-		if [ -n "${verbose}" ] ; then
-			echo "	target=\"${target}\""
-		fi
-
+		result=`/bin/sh ./config.sub ${target}`
+		target_cpu=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\1/'`
+		target_vendor=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\2/'`
+		target_os=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\3/'`
+		target=${target_cpu}-${target_vendor}-${target_os}
 		target_makefile_frag=config/tmake-${target}
 
 #### configure.in per-target parts come in here.
 
+case ${target_cpu} in
+sparc)
+	case ${target_vendor} in
+	sun) my_target=sun4 ;;
+	esac
+	;;
+m88k)	my_target=m88k-bcs ;;
+a29k)	my_target=coff-a29k ;;
+esac
+
+target_makefile_frag=config/tmake-${my_target}
+
+files=
+links=
 ## end of per-target part.
 
 		# Temporarily, we support only direct subdir builds.
@@ -323,11 +417,11 @@ for host in ${hosts} ; do
 		targetsubdir=Target-${target}
 
 		if [ -n "${removing}" ] ; then
-			if [ -n "${forcesubdirs}" ] ; then
+			if [ -n "${subdirs}" ] ; then
 				if [ -d "${hostsubdir}" ] ; then
 					rm -rf ${hostsubdir}/${targetsubdir}
 
-					if [ -z "`(ls ${hostsubdir}) 2>&1 | grep Target-`" ] ; then
+					if [ -z "`(ls ${hostsubdir}) 2>&1 | grep Target- | grep -v Target-independent`" ] ; then
 						rm -rf ${hostsubdir}
 					fi
 				else
@@ -337,24 +431,35 @@ for host in ${hosts} ; do
 				rm -f ${Makefile} config.status ${links}
 			fi
 		else
-			if [ -n "${forcesubdirs}" ] ; then
+			if [ -n "${subdirs}" ] ; then
 				# check for existing status before allowing forced subdirs.
 				if [ -f ${Makefile} ] ; then
-					echo "${Makefile} already exists in source directory.  `pwd` not configured."
+					echo '***' "${Makefile} already exists in source directory.  `pwd` not configured." 1>&2
 					exit 1
 				fi
 
 				if [ ! -d ${hostsubdir} ] ; then mkdir ${hostsubdir} ; fi
 				cd ${hostsubdir}
 
-				if [ ! -d ${targetsubdir} ] ; then mkdir ${targetsubdir} ; fi
+				if [ ! -d ${targetsubdir} ] ; then
+					if [ -z "${commontargets}" ] ; then
+						mkdir ${targetsubdir}
+					else
+						if [ ! -d Target-independent ] ; then
+							mkdir Target-independent
+						fi
+
+						${symbolic_link} Target-independent ${targetsubdir}
+					fi # if target independent
+				fi # if no target dir yet
+
 				cd ${targetsubdir}
 
 				srcdir=../..
 			else
 				# if not subdir builds, then make sure none exist.
 				if [ -n "`(ls .) 2>&1 | grep Host-`" ] ; then
-					echo "Configured subdirs exist.  `pwd` not configured."
+					echo '***' "Configured subdirs exist.  `pwd` not configured." 1>&2
 					exit 1
 				fi
 			fi
@@ -370,12 +475,12 @@ for host in ${hosts} ; do
 
 			if [ -n "${srctrigger}" -a ! -r ${srcdir}/${srctrigger} ] ; then
 				if [ -z "${srcdirdefaulted}" ] ; then
-					echo "${progname}: Can't find ${srcname} sources in `pwd`/${srcdir}" 1>&2
+					echo '***' "${progname}: Can't find ${srcname} sources in `pwd`/${srcdir}" 1>&2
 				else
-					echo "${progname}: Can't find ${srcname} sources in `pwd`/. or `pwd`/.." 1>&2
+					echo '***' "${progname}: Can't find ${srcname} sources in `pwd`/. or `pwd`/.." 1>&2
 				fi
 
-				echo \(At least ${srctrigger} is missing.\) 1>&2
+				echo '***' \(At least ${srctrigger} is missing.\) 1>&2
 				exit 1
 			fi
 
@@ -389,8 +494,8 @@ for host in ${hosts} ; do
 				set ${links}; link=$1; shift; links=$*
 
 				if [ ! -r ${srcdir}/${file} ] ; then
-					echo "${progname}: cannot create a link \"${link}\"," 1>&2
-					echo "since the file \"${file}\" does not exist." 1>&2
+					echo '***' "${progname}: cannot create a link \"${link}\"," 1>&2
+					echo '***' "since the file \"${file}\" does not exist." 1>&2
 					exit 1
 				fi
 
@@ -400,10 +505,13 @@ for host in ${hosts} ; do
 				${symbolic_link} ${srcdir}/${file} ${link} 2>/dev/null || ${hard_link} ${srcdir}/${file} ${link}
 
 				if [ ! -r ${link} ] ; then
-					echo "${progname}: unable to link \"${link}\" to \"${srcdir}/${file}\"." 1>&2
+					echo '***' "${progname}: unable to link \"${link}\" to \"${srcdir}/${file}\"." 1>&2
 					exit 1
 				fi
-				echo "Linked \"${link}\" to \"${srcdir}/${file}\"."
+
+				if [ -n "${verbose}" ] ; then
+					echo "Linked \"${link}\" to \"${srcdir}/${file}\"."
+				fi
 			done
 
 			# Create a .gdbinit file which runs the one in srcdir
@@ -439,7 +547,7 @@ for host in ${hosts} ; do
 			echo "host = ${host}" >> ${Makefile}
 			echo "target = ${target}" >> ${Makefile}
 
-			if [ -n "${forcesubdirs}" ] ; then
+			if [ -n "${subdirs}" ] ; then
 				echo "subdir = /${hostsubdir}/${targetsubdir}" >> ${Makefile}
 			else
 				echo "subdir =" >> ${Makefile}
@@ -496,7 +604,9 @@ for host in ${hosts} ; do
 				andusing=${using}
 			fi
 
-			echo "Created \"${Makefile}\"" in `pwd`${andusing}.
+			if [ -n "${verbose}" -o -z "${recursing}" ] ; then
+				echo "Created \"${Makefile}\"" in `pwd`${andusing}.
+			fi
 
 #### configure.in post-target parts come in here.
 
@@ -515,10 +625,30 @@ for host in ${hosts} ; do
 			originaldir=`pwd`
 			cd ${srcdir}
 		fi
+
+		# If there are subdirectories, then recurse. 
+		if [ -z "${norecurse}" -a -n "${configdirs}" ] ; then 
+			for configdir in ${configdirs} ; do
+				if [ -n "${verbose}" ] ; then
+					echo Configuring ${configdir}...
+				fi
+
+				if [ -d ${configdir} ] ; then
+					(cd ${configdir} ;
+						./configure -recursing ${host} +target=${target} \
+							${verbose} ${subdirs} ${removing} +destdir=${destdir}) \
+						| sed 's/^/	/'
+				else
+					if [ -n "${verbose}" ] ; then
+						echo Warning: directory \"${configdir}\" is missing.
+					fi
+				fi
+			done
+		fi
 	done # for each target
 
 	# Now build a Makefile for this host.
-	if [ -n "${forcesubdirs}" -a ! -n "${removing}" ] ; then
+	if [ -n "${subdirs}" -a ! -n "${removing}" ] ; then
 		cd ${hostsubdir}
 		cat > GNUmakefile << E!O!F
 # Makefile generated by configure for host ${host}.
@@ -534,91 +664,33 @@ E!O!F
 	fi
 done # for each host
 
-# If there are subdirectories, then recurse. 
-
-if [ -n "${norecurse}" -o -z "${configdirs}" ] ; then exit 0 ; fi
-
-# configdirs is not null
-for configdir in ${configdirs} ; do
-	echo Configuring ${configdir}...
-	specifics=
-	commons=
-
-	if [ -n "${defaulttargets}" ] ; then
-		for host in ${hosts} ; do
-			if [ -d ${configdir}.${host} ] ; then
-				newspecifics="${specifics} ${host}"
-				specifics=${newspecifics}
-			else
-				newcommons="${commons} ${host}"
-				commons=${newcommons}
-			fi # if target specific
-		done # for each host
-
-		if [ -n "${commons}" ] ; then
-			if [ -d ${configdir} ] ; then
-				(cd ${configdir} ;
-					./configure ${commons} ${verbose} ${forcesubdirs} ${removing} +destdir=${destdir}) \
-					| sed 's/^/	/'
-			else
-				echo Warning: directory \"${configdir}\" is missing.
-			fi
-		fi # if any common hosts
-
-		if [ -n "${specifics}" ] ; then
-			for host in ${specifics} ; do
-				echo Configuring target specific directory ${configdir}.${host}...
-				(cd ${configdir}.${host} ;
-					./configure ${host} ${verbose} ${forcesubdirs} ${removing} +destdir=${destdir}) \
-					| sed 's/^/	/'
-			done # for host in specifics
-		fi # if there are any specifics
-	else
-
-		for target in ${targets} ; do
-			if [ -d ${configdir}.${target} ] ; then
-				newspecifics="${specifics} ${target}"
-				specifics=${newspecifics}
-			else
-				newcommons="${commons} +target=${target}"
-				commons=${newcommons}
-			fi
-
-		done # check for target specific dir override
-
-		if [ -n "${verbose}" ] ; then
-			echo "	"commons=\"${commons}\"
-			echo "	"specifics=\"${specifics}\"
-		fi # if verbose
-
-		if [ -n "${commons}" ] ; then
-			if [ -d ${configdir} ] ; then
-				(cd ${configdir} ;
-					./configure ${hosts} ${verbose} ${forcesubdirs} ${removing} \
-						${commons} +destdir=${destdir}) \
-					| sed 's/^/	/'
-			else
-				echo Warning: directory \"${configdir}\" is missing.
-			fi
-		fi # if any commons
-
-		if [ -n "${specifics}" ] ; then
-			for target in ${specifics} ; do
-				echo Configuring target specific directory ${configdir}.${target}...
-				(cd ${configdir}.${target} ;
-					./configure ${hosts} ${verbose} ${forcesubdirs} ${removing} \
-						"+target=${target}" +destdir=${destdir}) \
-					| sed 's/^/	/'
-			done
-		fi # if any specifics
-	fi # not default targets
-done
-
 exit 0
 
 #
 # $Log$
-# Revision 1.16  1991/08/06 19:12:42  rich
+# Revision 1.20  1991/08/22 06:21:45  rich
+# Three part names & all.
+#
+# Revision 1.29  1991/08/20  04:56:51  rich
+# revisiting error messages
+#
+# Revision 1.28  1991/08/16  19:22:17  rich
+# This is the commontargets change and should be considered
+# experimental.
+#
+# Revision 1.27  1991/08/08  01:14:13  rich
+# allow +f to stand in for +subdirs
+#
+# Revision 1.26  1991/08/07  19:21:32  rich
+# +forcesubdirs -> +subdirs
+#
+# Revision 1.25  1991/08/07  07:05:30  rich
+# Added make.
+#
+# Revision 1.24  1991/08/06  19:26:01  rich
+# revised option parsing.
+#
+# Revision 1.23  1991/08/06  19:12:32  rich
 # Host-level GNUmakefiles.
 #
 # Revision 1.22  1991/07/20  01:22:30  rich
