* layout.cc (Layout::make_output_section): Call 	Target::new_output_section. 	(Layout::attach_allocated_section_to_segment): Put large section 	sections in a separate load segment with the large segment flag 	set. 	(Layout::segment_precedes): Sort large data segments after other 	load segments. 	(align_file_offset): New static function. 	(Layout::set_segment_offsets): Use align_file_offset. 	* output.h (class Output_section): Add is_small_section_ and 	is_large_section_ fields. 	(Output_section::is_small_section): New function. 	(Output_section::set_is_small_section):  New function. 	(Output_section::is_large_section): New function. 	(Output_section::set_is_large_section): New function. 	(Output_section::is_large_data_section): New function. 	(class Output_segment): Add is_large_data_segment_ field. 	(Output_segment::is_large_data_segment): New function. 	(Output_segment::set_is_large_data_segment): New function. 	* output.cc (Output_section::Output_section): Initialize new 	fields. 	(Output_segment::Output_segment): Likewise. 	(Output_segment::add_output_section): Add assertion that large 	data sections always go in large data segments.  Force small data 	sections to the end of the list of data sections.  Force small BSS 	sections to the start of the list of BSS sections.  For large BSS 	sections to the end of the list of BSS sections. 	* symtab.h (class Symbol): Declare is_common_shndx. 	(Symbol::is_defined): Check Symbol::is_common_shndx. 	(Symbol::is_common): Likewise. 	(class Symbol_table): Define enum Commons_section_type.  Update 	declarations.  Add small_commons_ and large_commons_ fields. 	* symtab.cc (Symbol::is_common_shndx): New function. 	(Symbol_table::Symbol_table): Initialize new fields. 	(Symbol_table::add_from_object): Put small and large common 	symbols in the right list. 	(Symbol_table::sized_finalized_symbol): Check 	Symbol::is_common_shndx. 	(Symbol_table::sized_write_globals): Likewise. 	* common.cc (Symbol_table::do_allocate_commons): Allocate new 	common symbol lists.  Don't call do_allocate_commons_list if the 	list is empty. 	(Symbol_table::do_allocate_commons_list): Remove is_tls 	parameter.  Add comons_section_type parameter.  Change all 	callers.  Handle small and large common symbols. 	* object.cc (Sized_relobj::do_finalize_local_symbols): Check 	Symbol::is_common_shndx. 	* resolve.cc (symbol_to_bits): Likewise. 	* target.h (Target::small_common_shndx): New function. 	(Target::small_common_section_flags): New function. 	(Target::large_common_shndx): New function. 	(Target::large_common_section_flags): New function. 	(Target::new_output_section): New function. 	(Target::Target_info): Add small_common_shndx, large_common_shndx, 	small_common_section_flags, and large_common_section_flags 	fields. 	(Target::do_new_output_section): New virtual function. 	* arm.cc (Target_arm::arm_info): Initialize new fields. 	* i386.cc (Target_i386::i386_info): Likewise. 	* powerpc.cc (Target_powerpc::powerpc_info) [all versions]: 	Likewise. 	* sparc.c (Target_sparc::sparc_info) [all versions]: Likewise. 	* x86_64.cc (Target_x86_64::x86_64_info): Likewise. 	(Target_x86_64::do_new_output_section): New function. 	* configure.ac: Define conditional MCMODEL_MEDIUM. 	* testsuite/Makefile.am (check_PROGRAMS): Add large. 	(large_SOURCES, large_CFLAGS, large_DEPENDENCIES): Define. 	(large_LDFLAGS): Define. 	* testsuite/large.c: New file. 	* testsuite/testfile.cc (Target_test::test_target_info): 	Initialize new fields. 	* configure, testsuite/Makefile.in: Rebuild.

diff --git a/gold/configure b/gold/configure
--- a/gold/configure
+++ b/gold/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar THREADS_TRUE THREADS_FALSE PLUGINS_TRUE PLUGINS_FALSE TARGETOBJS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE YACC RANLIB ac_ct_RANLIB LN_S USE_NLS LIBINTL LIBINTL_DEP INCINTL XGETTEXT GMSGFMT POSUB CATALOGS DATADIRNAME INSTOBJEXT GENCAT CATOBJEXT MKINSTALLDIRS MSGFMT MSGMERGE NATIVE_LINKER_TRUE NATIVE_LINKER_FALSE GCC_TRUE GCC_FALSE FN_PTRS_IN_SO_WITHOUT_PIC_TRUE FN_PTRS_IN_SO_WITHOUT_PIC_FALSE TLS_TRUE TLS_FALSE STATIC_TLS_TRUE STATIC_TLS_FALSE OMP_SUPPORT_TRUE OMP_SUPPORT_FALSE TLS_GNU2_DIALECT_TRUE TLS_GNU2_DIALECT_FALSE TLS_DESCRIPTORS_TRUE TLS_DESCRIPTORS_FALSE CONSTRUCTOR_PRIORITY_TRUE CONSTRUCTOR_PRIORITY_FALSE RANDOM_SEED_CFLAGS WARN_CFLAGS NO_WERROR WARN_CXXFLAGS LFS_CFLAGS LIBOBJS CPP EGREP HAVE_ZLIB_TRUE HAVE_ZLIB_FALSE CXXCPP MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar THREADS_TRUE THREADS_FALSE PLUGINS_TRUE PLUGINS_FALSE TARGETOBJS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE YACC RANLIB ac_ct_RANLIB LN_S USE_NLS LIBINTL LIBINTL_DEP INCINTL XGETTEXT GMSGFMT POSUB CATALOGS DATADIRNAME INSTOBJEXT GENCAT CATOBJEXT MKINSTALLDIRS MSGFMT MSGMERGE NATIVE_LINKER_TRUE NATIVE_LINKER_FALSE GCC_TRUE GCC_FALSE FN_PTRS_IN_SO_WITHOUT_PIC_TRUE FN_PTRS_IN_SO_WITHOUT_PIC_FALSE MCMODEL_MEDIUM_TRUE MCMODEL_MEDIUM_FALSE TLS_TRUE TLS_FALSE STATIC_TLS_TRUE STATIC_TLS_FALSE OMP_SUPPORT_TRUE OMP_SUPPORT_FALSE TLS_GNU2_DIALECT_TRUE TLS_GNU2_DIALECT_FALSE TLS_DESCRIPTORS_TRUE TLS_DESCRIPTORS_FALSE CONSTRUCTOR_PRIORITY_TRUE CONSTRUCTOR_PRIORITY_FALSE RANDOM_SEED_CFLAGS WARN_CFLAGS NO_WERROR WARN_CXXFLAGS LFS_CFLAGS LIBOBJS CPP EGREP HAVE_ZLIB_TRUE HAVE_ZLIB_FALSE CXXCPP MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LTLIBOBJS'
 ac_subst_files=''
 ac_pwd=`pwd`
 
@@ -4603,6 +4603,17 @@ else
 fi
 
 
+
+
+if test "$target_cpu" = "x86_64"; then
+  MCMODEL_MEDIUM_TRUE=
+  MCMODEL_MEDIUM_FALSE='#'
+else
+  MCMODEL_MEDIUM_TRUE='#'
+  MCMODEL_MEDIUM_FALSE=
+fi
+
+
 echo "$as_me:$LINENO: checking for thread support" >&5
 echo $ECHO_N "checking for thread support... $ECHO_C" >&6
 if test "${gold_cv_c_thread+set}" = set; then
@@ -7651,6 +7662,13 @@ echo "$as_me: error: conditional \"FN_PTRS_IN_SO_WITHOUT_PIC\" was never defined
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${MCMODEL_MEDIUM_TRUE}" && test -z "${MCMODEL_MEDIUM_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MCMODEL_MEDIUM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"MCMODEL_MEDIUM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${TLS_TRUE}" && test -z "${TLS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"TLS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -8335,6 +8353,8 @@ s,@GCC_TRUE@,$GCC_TRUE,;t t
 s,@GCC_FALSE@,$GCC_FALSE,;t t
 s,@FN_PTRS_IN_SO_WITHOUT_PIC_TRUE@,$FN_PTRS_IN_SO_WITHOUT_PIC_TRUE,;t t
 s,@FN_PTRS_IN_SO_WITHOUT_PIC_FALSE@,$FN_PTRS_IN_SO_WITHOUT_PIC_FALSE,;t t
+s,@MCMODEL_MEDIUM_TRUE@,$MCMODEL_MEDIUM_TRUE,;t t
+s,@MCMODEL_MEDIUM_FALSE@,$MCMODEL_MEDIUM_FALSE,;t t
 s,@TLS_TRUE@,$TLS_TRUE,;t t
 s,@TLS_FALSE@,$TLS_FALSE,;t t
 s,@STATIC_TLS_TRUE@,$STATIC_TLS_TRUE,;t t
